# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home1"
url = "/"
[main.params]
icon = "home"
newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/C9QuaRtz"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "bilibili"
name = "bilibili"
url = "https://space.bilibili.com/620599492"

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "Steam"
name = "Steam"
url = "https://steamcommunity.com/profiles/76561198842028671"

[social.params]
icon = "brand-steam"